name: linting, testing, buildings
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --force
      - name: build production project
        if: always()
        run: npm run build:prod      
      - name: linting typescript
        if: always()
        run: npm run eslint
      - name: linting scss
        if: always()
        run: npm run stylelint
      - name: unit testing
        if: always()
        run: npm run jest
      - name: ui testing
        if: always()
        run: npm run test:ui:ci

      
      
